name: Build development client

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        options:
          - android
          - ios
          - all
        default: android
        required: true

jobs:
  build_android:
    if: ${{ inputs.platform == 'android' || inputs.platform == 'all' }}
    type: build
    params:
      platform: android
      profile: development

  build_ios:
    if: ${{ inputs.platform == 'ios' || inputs.platform == 'all' }}
    type: build
    params:
      platform: ios
      profile: development
